language: java

# this will make travis use java 1.8.xxx
jdk:
- oraclejdk8

after_success:
- ./gradlew jacocoTestReport coveralls

deploy:
  provider: heroku
  api_key:
    secure: "d11dcc23-39fd-4020-b00a-2b25b10db3af"
  app: codeheroes