language: java

# this will make travis use java 1.8.xxx
jdk:
- oraclejdk8


# firefox for cucumber-selenium testing
addons:
   
  firefox: "49.0"


before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3

before_install:
  - wget https://github.com/mozilla/geckodriver/releases/download/v0.15.0/geckodriver-v0.15.0-linux64.tar.gz
  - mkdir geckodriver
  - tar -xzf geckodriver-v0.15.0-linux64.tar.gz -C geckodriver
  - export PATH=$PATH:$PWD/geckodriver

after_success:
- ./gradlew jacocoTestReport coveralls

deploy:
  provider: heroku
  api_key:
    secure: "d11dcc23-39fd-4020-b00a-2b25b10db3af"
  app: codeheroes